  - name: Download mysql_replication.py
    get_url: 
      url: https://raw.github.com/racker/rackspace-monitoring-agent-plugins-contrib/master/mysql_replication.py
      dest: /usr/lib/rackspace-monitoring-agent/plugins/mysql_replication.py
      mode: 0744
      owner: root
      group: root
    notify: restart rackspace-monitoring-agent

  - name: Copy mysql_replication.yaml
    copy: src=mysql_replication.yaml dest=/etc/rackspace-monitoring-agent.conf.d/
    notify: restart rackspace-monitoring-agent
